config/routes.rb
Rails.application.routes.draw do

  resources :meetings
  resources :documents
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :messages do  
    resources :comments
  end
  
  get 'dashboard_bookkeepers/index'

  devise_for :bookkeepers
  get 'dashboards/index'

  devise_for :users, controllers: { registrations: "registrations" }
  get 'pages/index'
  get 'pages/pricing'
  get 'pages/testimonials'
  get 'pages/careers'
  get 'pages/faq'
  get 'pages/security'
  get 'pages/contact'
  
  resources :after_register
  
  
  scope :users do
    root :to => 'dashboards#index', :as => :user_root
  end
  
  scope :bookkeepers do
    root :to => 'dashboard_bookkeepers#index', :as => :bookkeeper_root
  end
  
  root 'pages#index'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:calendly_meeting_url, :bookkeeper_name)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= simple_form_for(@meeting) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :bookkeeper_name %>
    <%= f.input :calendly_meeting_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>Editing Meeting Info</h1>
            <%= render 'form' %>

            <%= link_to 'Show', @meeting %> |
            <%= link_to 'Back', meetings_path %>            
        </div>
    </div>
</div>

app/views/meetings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>Book a Meeting</h2>
    </div><!-- end col-md-12 -->
  </div><!-- end row -->
  <div class="row">
    <div class="col-md-12">
      <% @meetings.each do |meeting| %>
      <div class="well well-lg">
        <h4>Book a meeting with <%= meeting.bookkeeper_name %></h4>
        <p>
          <%= link_to meeting, class: "btn btn-primary btn-lg active" do %>
            <i class="fa fa-calendar"></i> Show <%= meeting.bookkeeper_name %>'s Calendar
          <% end %>
        </p>  
        <% if current_user.admin? %>
          <p><%= link_to 'Edit', edit_meeting_path(meeting) %></p>
          <p><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <% end %>
      </div>
      
        
        
    <% end %>
    </div><!-- end col-md-12 -->
  </div><!-- end row -->
  <%= link_to 'New Meeting', new_meeting_path if current_user.admin? %>
</div><!-- end container -->

app/views/meetings/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <p style="color: red;"><em>For testing purposes, type any name and copy this below: mothers-bookkeeper-1-on-1 as Calendly meeting URL</em></p>
            <%= render 'form' %>
            <%= link_to 'Back', meetings_path %>
        </div>
    </div>
</div>

app/views/meetings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="calendly-inline-widget" data-url="https://calendly.com/mothers-test/<%= @meeting.calendly_meeting_url %>" style="min-width:320px;height:580px;"></div>
      <script type="text/javascript" src="https://calendly.com/assets/external/widget.js"></script>
    </div><!-- col-md-12 -->
  </div><!-- row -->
  <% if current_user.admin? %>
    <%= link_to 'Edit', edit_meeting_path(@meeting) %> |
    <%= link_to 'Back', meetings_path %>
  <% end %>
</div><!-- container -->