config/routes.rb
Rails.application.routes.draw do

  resources :meetings
  resources :documents
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :messages do  
    resources :comments
  end
  
  get 'dashboard_bookkeepers/index'

  devise_for :bookkeepers
  get 'dashboards/index'

  devise_for :users, controllers: { registrations: "registrations" }
  get 'pages/index'
  get 'pages/pricing'
  get 'pages/testimonials'
  get 'pages/careers'
  get 'pages/faq'
  get 'pages/security'
  get 'pages/contact'
  
  resources :after_register
  
  
  scope :users do
    root :to => 'dashboards#index', :as => :user_root
  end
  
  scope :bookkeepers do
    root :to => 'dashboard_bookkeepers#index', :as => :bookkeeper_root
  end
  
  root 'pages#index'

end

app/models/document.rb
class Document < ActiveRecord::Base
    mount_uploader :attachment, AttachmentUploader
    belongs_to :user
    has_many :messages
    validates_presence_of :title, :requested_by
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    #@document = Document.new
    @document = current_user.documents.build
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    #@document = Document.new(document_params)
    @document = current_user.documents.build(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: "#{@document.title} was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: "#{@document.title} was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: "#{@document.title} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:title, :description, :attachment, :requested_by, :due_date_by, :verified_by_bookkeeper, :mail_instead)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= simple_form_for(@document) do |f| %>

  <div class="form-inputs">
    <% if current_user.admin? %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :requested_by %>
      <%= f.input :due_date_by, :as => :date_picker %>
      <%= f.input :verified_by_bookkeeper, 
                            :as => :select, 
                            :collection => [['No',false],['Yes',true]], 
                            :include_blank => false, 
                            :label => "Verified by Bookkeeper?" %>
    <% end %>
    
    <p style="margin-top: 30px;"><small><em>Please choose one of the following options. Select "Yes" if you wish to send documents by mail, or upload document below.</em></small></p>
    <%= f.input :mail_instead, :as => :select, 
                          :collection => [['No',false],['Yes',true]], 
                          :include_blank => false, 
                          :label => "Mail instead?" %>
                              
    <%= f.input :attachment, input_html: { hidden: true }, label: 'Upload Attachment' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h3>Document Upload</h3>
            <%= render 'form' %>
            <%= link_to 'Show', @document %> |
            <%= link_to 'Back', documents_path %>
        </div>
    </div>
</div>

app/views/documents/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>Document Requests</h2>
    </div><!-- end col-md-12 -->
    <div class="col-md-12">
      <table class="table table-striped">
  <thead>
    <tr>
      <th>Requested By</th>
      <th>Requeste Date</th>
      <th>Title</th>
      <th>Doc Description</th>
      <th>Doc Status</th>
      <th>Download File</th>
      <th colspan="2"></th>
      <th>Due Date</th>
      <th>Verified</th>
      <th>Messages</th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.requested_by %></td>
        <td><%= document.created_at %></td>
        <td><%= document.title %></td>
        <td><%= document.description %></td>
        <% if document.attachment.url.blank? && document.mail_instead == false %>
          <td><p class="btn btn-default btn-xs"><i class="fa fa-map-marker"></i> Mail/Upload Document</p></td>
        <% elsif (document.attachment.url.blank? && document.mail_instead == true) %>
          <td>
            <a tabindex="0" class="btn btn-primary btn-xs" role="button" data-toggle="popover" data-trigger="focus" data-placement="top" title="Ship to address below" data-content="301 Maude Road, Port Moody BC, V3H5B1 Canada"><i class="fa fa-envelope-o"></i> Shipping Address</a>
             
            
          </td>
        <% elsif document.attachment.url.present? && document.mail_instead == false %>
          <td><p class="btn btn-success btn-xs"><i class="fa fa-check"></i> Document Uploaded</p></td>
        <% end %>
        <% if document.attachment.present? %>
          <td>
            <%= link_to document.attachment.url, class: "btn btn-primary btn-xs" do %>
              <i class="fa fa-file-text-o"></i> Download File
            <% end %>
          </td>
        <% else %>
          <td><p class="btn btn-danger btn-xs"><i class="fa fa-ban"></i> File Not Uploaded</p></td>
        <% end %>
        <td><%# link_to 'Show', document %></td>
        <td>
          <% if document.attachment.blank? %>
            <%= link_to edit_document_path(document), class: "btn btn-info btn-xs" do %>
              <i class="fa fa-cloud-upload"></i> Upload
            <% end %>
          <% else %>
            <%= link_to edit_document_path(document), class: "btn btn-warning btn-xs" do %>
              <i class="fa fa-pencil-square-o"></i> Modify
            <% end %>
          <% end %>
        </td>
        <td><%= document.due_date_by %></td>
        <% if document.verified_by_bookkeeper == true %>
          <td class="text-center"><i class="fa fa-check" style="color: green;"></i></td>
        <% elsif document.verified_by_bookkeeper == false %>
          <td class="text-center"><i class="fa fa-times" style="color: red;"></i></td>
        <% end %>
        <td>
          <%= link_to document_path(document) do %>
            <i class="fa fa-comments-o"></i> Show
          <% end %>
        </td>
        
        <% if current_user.admin? %>
          <td><%= link_to 'Delete', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

    <% if current_user.admin? %>
      <%= link_to 'New Document Request', new_document_path, class: "btn btn-success" %>
    <% end %>

    </div><!-- end col-md-12 -->
  </div><!-- end row -->
</div><!-- end container -->

app/views/documents/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h3>New Document Request</h3>
            <%= render 'form' %>
            <%= link_to 'Back', documents_path %>
        </div>
    </div>
</div>

app/views/documents/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
      <%= link_to 'Back', documents_path %>
      <h2><%= @document.title %></h2>
      <p><%= @document.description %></p>
      <hr>
      
      <%= link_to 'Edit', edit_document_path(@document) if current_user.admin? %>
      

    </div><!-- end col-md-12 -->
  </div><!-- end row -->
  
 
  
</div><!-- end container -->