config/routes.rb
Rails.application.routes.draw do

  resources :meetings
  resources :documents
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :messages do  
    resources :comments
  end
  
  get 'dashboard_bookkeepers/index'

  devise_for :bookkeepers
  get 'dashboards/index'

  devise_for :users, controllers: { registrations: "registrations" }
  get 'pages/index'
  get 'pages/pricing'
  get 'pages/testimonials'
  get 'pages/careers'
  get 'pages/faq'
  get 'pages/security'
  get 'pages/contact'
  
  resources :after_register
  
  
  scope :users do
    root :to => 'dashboards#index', :as => :user_root
  end
  
  scope :bookkeepers do
    root :to => 'dashboard_bookkeepers#index', :as => :bookkeeper_root
  end
  
  root 'pages#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    
    if user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :dashboard              # grant access to the dashboard
      can :manage, :all
      can :manage, Document
      can :manage, Meeting
    elsif user.client_admin?
      can :read, :all
      can :manage, Message
      can :read, Document
      can :update, Document
      can :read, Meeting
    else 
      can :read, :all
      can :manage, Message
      can :read, Document
      can :update, Document
      can :read, Meeting
    end
    #if user.has_role? :admin
    #  can :access, :rails_admin   # grant access to rails_admin
    #  can :dashboard              # grant access to the dashboard
    #  can :manage, :all
    #else
    #  can :read, :all
    #end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
  
end

app/models/bookkeeper.rb
class Bookkeeper < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :message
  belongs_to :document
end

app/models/document.rb
class Document < ActiveRecord::Base
    mount_uploader :attachment, AttachmentUploader
    belongs_to :user
    has_many :messages
    validates_presence_of :title, :requested_by
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
    #resourcify
    validates :user_id, presence: true
    validates :title, presence: true
    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  #rolify
  #ROLES = %i[admin client_admin client]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :messages
  has_many :comments, dependent: :destroy
  has_many :documents
  
  #after_create :send_notification
  
  #def send_notification
    #AdminMailer is our mailer that we created, (self) is the current user who just registered, and .deliver is actually doing delivery of emails
   # AdminMailer.new_user(self).deliver 
  #end
         
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    #@accounts = Account.all
    @accounts = current_user.accounts
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    #@account = Account.new
    @account = current_user.accounts.build
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    #@account = Account.new(account_params)
    @account = current_user.accounts.build(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to new_question_path, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:first_name, :last_name, :company_name, :phone_number, :address, :card_number, :name_on_card, :expiry, :cvc, :billing_posta_code)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_message

    def create  
      @comment = @message.comments.build(comment_params)
      @comment.user_id = current_user.id
    
      if @comment.save
        flash[:success] = "You commented the hell out of that message!"
        redirect_to :back
      else
        flash[:alert] = "Check the comment form, something went horribly wrong."
        render root_path
      end
    end
    
    def destroy  
      @comment = @message.comments.find(params[:id])
    
      @comment.destroy
      flash[:success] = "Comment deleted :("
      redirect_to messages_path
    end
    
    private
    
    def comment_params  
      params.require(:comment).permit(:content)
    end
    
    def set_message 
      @message = Message.find(params[:message_id])
    end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def pricing
  end

  def testimonials
  end

  def careers
  end

  def faq
  end

  def security
  end

  def contact
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/after_register_helper.rb
module AfterRegisterHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/_alert.html.erb
<div class="alert text-center 
    <%= 
    case type.to_sym 
    when :alert, :danger, :error, :validation_errors
        'alert-danger'
    when :warning, :todo
        'alert-warning'
    when :notice, :success
        'alert-success'
    else 
        'alert-info'
    end
    %>
     alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= content %>
</div>

app/views/layouts/_bookkeeper_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Mothers Bookkeeping', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Pricing', pages_pricing_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Details <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Testimonials', pages_testimonials_path %></li>
            <li><%= link_to 'Careers', pages_careers_path %></li>
            <li><%= link_to 'FAQ', pages_faq_path %></li>
            <li><%= link_to 'Blog', '#' %></li>
            <li><%= link_to 'Security', pages_security_path %></li>
          </ul>
        </li>
        <li><%= link_to 'Contact', pages_contact_path %></li>
        <% if bookkeeper_signed_in? %>
          <li><%= link_to('Logout', destroy_bookkeeper_session_path, :method => :delete) %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_general_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Mothers Bookkeeping', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Pricing', pages_pricing_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Details <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Testimonials', pages_testimonials_path %></li>
            <li><%= link_to 'Careers', pages_careers_path %></li>
            <li><%= link_to 'FAQ', pages_faq_path %></li>
            <li><%= link_to 'Blog', '#' %></li>
            <li><%= link_to 'Security', pages_security_path %></li>
          </ul>
        </li>
        <li><%= link_to 'Contact', pages_contact_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        <% else %>
          <li><%= link_to 'Get Started', new_user_registration_path %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_user_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Mothers Bookkeeping', dashboards_index_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', dashboards_index_path %></li>
        <li><%= link_to 'My Messages', messages_path %></li>
        <li><%= link_to 'My Reports', '#' %></li>
        <li><%= link_to 'My Documents', documents_path %></li>
        <li><%= link_to 'Book a Meeting', meetings_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Manage My Account', edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>    
            
          </ul>
        </li>
        
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mothers Bookkeeping</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <%= render 'layouts/user_nav' %>
<% elsif bookkeeper_signed_in? %>
  <%= render 'layouts/bookkeeper_nav' %>
<% else %>
  <%= render 'layouts/general_nav' %>
<% end %>

<% flash.each do |type, content| %>
    <% if content.respond_to?('each') 
        content.each do |item| %>
            <%= render 'layouts/alert', 
                type: type,
                content: item %>
        <% end %>
    <% else %>
        <%= render 'layouts/alert', 
                type: type,
                content: content %>
    <% end %>

<% end %>


<%= yield %>

</body>
</html>

app/views/pages/careers.html.erb
<h1>Pages#careers</h1>
<p>Find me in app/views/pages/careers.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
              <h1>Welcome to Mothers Bookkeeping</h1>
              <p>Best place for your bookkeeping needs</p>
              <p><%= link_to "Get Started", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
            </div>            
        </div>
    </div><!-- end row -->
    <div class="row">
        <div class="col-md-12">
            <h3>Login accounts</h3>
            <p><strong>Mothers Admin:</strong> Username: admin@mail.com | Password: demo1234</p>
            <p><strong>Client Admin:</strong> Username: client_admin@mail.com | Password: demo1234</p>
            <p><strong>Client:</strong> Username: client@mail.com | Password: demo1234</p>
        </div>
    </div>
</div>

app/views/pages/pricing.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h4>Every plan comes with a dedicated bookkeeping team to handle your monthly books and simple software to let you keep track of your financials.</h4>
        </div>
    </div>
    <div class="row" style="margin-top: 50px;">
        <div class="col-xs-12 col-md-4">
            <div class="panel-table panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Starter</h3>
                </div>
                <div class="panel-table-body">
                    <div class="the-price">
                        <h1>
                            $495<span class="subscript">/mo</span></h1>
                        <small>Great for up to $200k/year revenue</small>
                    </div>
                    <table class="table">
                        <tr>
                            <td>
                                1 Account
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                1 Project
                            </td>
                        </tr>
                        <tr>
                            <td>
                                100K API Access
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                100MB Storage
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Custom Cloud Services
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                Weekly Reports
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="panel-footer">
                    <%= link_to "Get Started", new_user_registration_path, class: "btn btn-success" %>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-4">
            <div class="panel-table panel-success">
                <div class="cnrflash">
                    <div class="cnrflash-inner">
                        <span class="cnrflash-label">MOST
                            <br>
                            POPULR</span>
                    </div>
                </div>
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Grower</h3>
                </div>
                <div class="panel-table-body">
                   <div class="the-price">
                        <h1>
                            $695<span class="subscript">/mo</span></h1>
                        <small>Great for mid size companies</small>
                    </div>
                    <table class="table">
                        <tr>
                            <td>
                                2 Account
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                5 Project
                            </td>
                        </tr>
                        <tr>
                            <td>
                                100K API Access
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                200MB Storage
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Custom Cloud Services
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                Weekly Reports
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="panel-footer">
                    <%= link_to "Get Started", new_user_registration_path, class: "btn btn-success" %>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-4">
            <div class="panel-table panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Gold</h3>
                </div>
                <div class="panel-table-body">
                    <div class="the-price">
                        <h1>
                            $1,695<span class="subscript">/mo</span></h1>
                        <small>Great for corporate accounts</small>
                    </div>
                    <table class="table">
                        <tr>
                            <td>
                                5 Account
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                20 Project
                            </td>
                        </tr>
                        <tr>
                            <td>
                                300K API Access
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                500MB Storage
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Custom Cloud Services
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                Weekly Reports
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="panel-footer">
                    <%= link_to "Get Started", new_user_registration_path, class: "btn btn-success" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/security.html.erb
<h1>Pages#security</h1>
<p>Find me in app/views/pages/security.html.erb</p>

app/views/pages/testimonials.html.erb
<h1>Pages#testimonials</h1>
<p>Find me in app/views/pages/testimonials.html.erb</p>